version: '3.9'

services:
  socks_proxy_server:
    tty: true
    stdin_open: true
    hostname: socks_proxy_server
    build:
      context: .
    networks:
      - conviso-nw
    volumes:
      - ./machine/.ssh:/home/uzer/.ssh

networks:
  # The network must be shared with some other service in which you want to pass through the Socks
  conviso-nw:
    external: true
